export const COLORS = {
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primaryLight: '#DBEAFE',
  secondary: '#F59E0B',
  secondaryDark: '#D97706',
  secondaryLight: '#FEF3C7',
  accent: '#10B981',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  surfaceSubdued: '#EFF6FF',
  textPrimary: '#0F172A',
  textSecondary: '#475569',
  textMuted: '#64748B',
  success: '#16A34A',
  successLight: '#DCFCE7',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  error: '#DC2626',
  errorLight: '#FEE2E2',
  errorText: '#B91C1C',
  review: '#7C3AED',
  reviewLight: '#EDE9FE',
  border: '#E2E8F0',
  borderFocus: '#2563EB',
};

export const SIZES = {
  xs: 4,
  base: 8,
  small: 12,
  medium: 16,
  large: 20,
  xlarge: 24,
  xxlarge: 32,
  hero: 48,
  minTouchTarget: 48,
  cardRadius: 20,
  buttonRadius: 26,
  inputRadius: 14,
  pillRadius: 999,
};

export const SHADOWS = {
  small: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
};
