export enum SubmissionStatus {
  CREATED = 'CREATED',
  IMAGE_UPLOADED = 'IMAGE_UPLOADED',
  PROCESSING = 'PROCESSING',
  PROPOSED_GRADE = 'PROPOSED_GRADE',
  NEEDS_CONFIRMATION = 'NEEDS_CONFIRMATION',
  NEEDS_RETAKE = 'NEEDS_RETAKE',
  CROP_REQUIRED = 'CROP_REQUIRED',
  FEEDBACK_READY = 'FEEDBACK_READY',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  OUT_OF_SCOPE = 'OUT_OF_SCOPE',
  TEACHER_APPROVED = 'TEACHER_APPROVED',
  TEACHER_OVERRIDDEN = 'TEACHER_OVERRIDDEN',
  FAILED = 'FAILED'
}

export enum Decision {
  VALID = 'VALID',
  INVALID = 'INVALID',
  UNCERTAIN = 'UNCERTAIN'
}

export enum OperationType {
  VERTICAL_ADDITION = 'VERTICAL_ADDITION',
  VERTICAL_SUBTRACTION = 'VERTICAL_SUBTRACTION'
}

export enum ErrorType {
  COMPUTATION_ERROR = 'COMPUTATION_ERROR',
  CARRY_BORROW_ERROR = 'CARRY_BORROW_ERROR',
  PLACE_VALUE_ALIGNMENT_ERROR = 'PLACE_VALUE_ALIGNMENT_ERROR',
  NOTATION_ISSUE = 'NOTATION_ISSUE'
}

export enum ImageQualityIssue {
  BLUR = 'BLUR',
  DARK = 'DARK',
  GLARE = 'GLARE',
  SKEW = 'SKEW',
  INCOMPLETE_CROP = 'INCOMPLETE_CROP'
}

export enum ReviewReason {
  LOW_RECOGNITION_CONFIDENCE = 'LOW_RECOGNITION_CONFIDENCE',
  LOW_STRUCTURE_CONFIDENCE = 'LOW_STRUCTURE_CONFIDENCE',
  LOW_DIAGNOSIS_CONFIDENCE = 'LOW_DIAGNOSIS_CONFIDENCE',
  IMAGE_QUALITY = 'IMAGE_QUALITY',
  AMBIGUOUS_TOKEN = 'AMBIGUOUS_TOKEN',
  RULE_CONFLICT = 'RULE_CONFLICT',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  MANUAL_REVIEW_REQUIRED = 'MANUAL_REVIEW_REQUIRED'
}

export enum TeacherDecisionType {
  APPROVE = 'APPROVE',
  OVERRIDE = 'OVERRIDE'
}

export enum BatchStatus {
  CREATED = 'CREATED',
  UPLOADING = 'UPLOADING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED'
}
