export const MATHVISION_COLORS = {
  primary: '#7055F6',
  primaryDark: '#5637C9',
  primaryLight: '#EDE9FF',
  secondary: '#F59E0B',
  secondaryDark: '#D97706',
  secondaryLight: '#FEF3C7',
  accent: '#10B981',
  background: '#F8F7FE',
  surface: '#FFFFFF',
  surfaceSubdued: '#F0EDFF',
  textPrimary: '#18164C',
  textSecondary: '#475569',
  textMuted: '#64748B',
  success: '#16A34A',
  successLight: '#DCFCE7',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  error: '#DC2626',
  errorLight: '#FEE2E2',
  errorText: '#B91C1C',
  review: '#7C3AED',
  reviewLight: '#EDE9FE',
  border: '#E2E8F0',
  borderFocus: '#7055F6',
  pastelBlue: '#EFF6FF',
  pastelGreen: '#F0FDF4',
  pastelPeach: '#FFF7ED',
  pastelPurple: '#FAF5FF',
  pastelAmber: '#FEFCE8',
  rawOcrBg: '#F1F5F9',
  rawOcrBorder: '#CBD5E1',
  rawOcrText: '#334155',
  rawOcrLabel: '#64748B',
  aiSuggestionBg: '#FEF3C7',
  aiSuggestionBorder: '#FCD34D',
  aiSuggestionText: '#92400E',
  aiSuggestionLabel: '#D97706',
  finalResultBg: '#EFF6FF',
  finalResultBorder: '#3B82F6',
  finalResultText: '#1E3A8A',
  finalResultLabel: '#1D4ED8',
  reasonBg: '#F8FAFC',
  reasonBorder: '#E2E8F0',
  reasonText: '#475569',
  reasonLabel: '#0F172A',
};

export const COLORS = MATHVISION_COLORS;
export function getThemeColors() { return COLORS; }

export const SIZES = {
  xs: 4,
  base: 8,
  small: 12,
  medium: 16,
  large: 20,
  xlarge: 24,
  xxlarge: 32,
  hero: 48,
  minTouchTarget: 48,
  radiusSm: 8,
  radiusMd: 14,
  radiusLg: 20,
  radiusXl: 24,
  cardRadius: 20,
  buttonRadius: 26,
  inputRadius: 14,
  pillRadius: 999,
};

export const SHADOWS = {
  small: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
};
